#!/usr/bin/env bash

# Wrapper for running a command and measure timing using GNU time.
#  Output: "%e\t%U\t%S"

exec 3>&1 4>&2
res=$({ /usr/bin/time -f "%e\t%U\t%S" "$@" | cat >/dev/null; } 2>&1)
exec 3>&- 4>&-

echo "$res"