name: Test Executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup gcc
      uses: egor-tensin/setup-gcc@v1

    - name: install dependencies
      run: sudo apt update && sudo apt install -y apt-utils build-essential git make cmake libzstd-dev liblz4-dev grep

    - name: install boost
      run: sudo apt update && sudo apt install -y libboost-dev libboost-program-options-dev

    - name: git submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRE2_BUILD_TESTING=off -DEXE_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --label-regex ".*exe_test"
